spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: admin
  application:
    name: Spring-boot-tutorial
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome to daily code buffer
server:
  port: '8082'
